<?php

require_once "Customer.php";
require_once "Constants.php";

// Pass the Customer ID as the constructor argument.
$customer = new Customer("1");

/* This example demonstrates the minimum fields needed for 
 * creating a new credit card. */

$address = Array( 
        "Customer" => "Herb Caen", // Customer ID.
        "Line1" => "600 Ellis Street", 
        "City" => "San Francisco",
        "State" => "CA", 
        "Country" => "USA", 
        "Zip" => "94109"
);

$cardholder = Array( 
        "FirstName" => "Herb",
        "LastName" => "Caen"
);

$creditCard = Array(
        "Tender" => Constants::TENDER_TYPE_CREDIT_CARD, // "CreditCard" | "ECheck"
        "Customer" => $customer->getId(), // Customer ID generated by PayFabric
        "Account" => "4032030806166550", // Credit card number.
        "ExpDate" => "0719", // MMYY format.
        "CardHolder" => $cardholder, 
        "Billto" => $address
);

/* Tip: throws missingRequiredCardFieldException, missingRequiredCardholderFieldException,
 * or missingRequiredAddressFieldException when you submit a credit card array
 * that is missing any of the required fields demonstrated above. */
$customer->createCreditCard($creditCard);
